all:
	essi -f main0.fei
	essi -f main1.fei
	essi -f main2.fei
	essi -f main3.fei
	essi -f main4.fei
	essi -f main5.fei
	essi -f main6.fei
	essi -f main7.fei
	essi -f main8.fei
	essi -f main9.fei
	essi -f main10.fei
clean:
	rm *.feioutput